### PR TITLE
add savannah, update dependencies

### PR DESCRIPTION
**Pull request by carlvlewis**

### CODE REVIEW

**Comment by carlvlewis** [comment]
Seems to be issue with Travis CI.

**Comment by carlvlewis** [comment]
Seeing as it doesn't appear this app is being maintained anymore, we redeployed our own instance at http://click-that-hood.opensavannah.org.

**Comment by tdooner** [comment]
Hey @carlvlewis, are you all seeing a user need for this? Would love to discuss transferring maintenance of this repository over to somebody who is still working on improving it for users.

**Comment by carlvlewis** [comment]
No, wouldn't say a there's a user need *per se*, but it's helpful to have, as Savannah has something like 107 neighborhood associations that all have similar issues but never collaborate. A need exists to educate people on their local neighborhoods so that they might get involved with their neighborhood association as well as a need for cross-neighborhood collaboration. Just saw this as possibly part of helping fulfill that gap. Happy to maintain and improve it – don't know if it will be feasible for it to work on mobile, though, as the data density required to use the application won't be usable on a smaller viewport.

**Comment by k-nut** [comment]
I think there is quite some interest from the community in this. I would personally be very happy if someone could take over maintenance of the repository. Since most PRs will probably be about adding new maps having a working sanity check on Travis should help a lot and reduce the manual effort to a minimum.
I'd be happy to help triage the old bugs and fix Travis so that the existing PRs can be merged.

**Comment by carlvlewis** [comment]
Hey @tdooner! Pardon the delayed responses as of late. Sure, this is something I think should be maintained and possibly improved upon even. Yes, the Travis CI failures are cringe-inducing for me, so if you think you could clear those up, I'd be more than happy to manage PRs of new geojson files as well as (possibly) perform some minor interface improvements for the small neighborhoods and make sure all dependencies stay intact and working.

**Comment by specious** [comment]
I'd love to be a maintainer for this project. My pull requests #294 and #295 have been waiting to get reviewed since June 2016.

I promise to promptly review all the contributions waiting in the queue.

**Comment by melynnduh** [comment]
I had emailed about adding Allegheny County, PA to this list. Since I am a newbie with Github, I didn't have a pull request -- I had emailed the files instead. How should I go about submitting Allegheny County files without greatly troubling you to update?

**Comment by specious** [comment]
@melynnduh, take a look at some of the [submitted pull requests](https://github.com/codeforamerica/click_that_hood/pulls). Check the "Files changed" tab to see how they're done. If you're new to forking a repository, GitHub has [excellent tutorials](https://help.github.com/articles/fork-a-repo/).

Any specific questions are par for the course too. You're probably not the only one wondering.

**Comment by specious** [comment]
@tdooner, we need a maintainer.  Would you consider me competent?

**Comment by fnogatz** [comment]
Hi there! We recently transferred this repository and the domain `click-that-hood.com` from @codeforamerica to the @codeforgermany namespace and intend to bring it to life again :) Are some of you still interested to join us in maintaining code and data? Ping @k-nut, @carlvlewis, @specious, @melynnduh.

**Comment by specious** [comment]
@fnogatz, that's excellent news. Count me in.

**Comment by fnogatz** [comment]
Added you to the repository, @specious.

**Comment by specious** [comment]
@carlvlewis, thank you for this contribution. I just cherry picked the [data files for Savannah](https://github.com/codeforgermany/click_that_hood/blob/6e6a9fcf012a3304e18403adab898aca14937a0b/public/data/savannah.geojson) and merged them into master.

Merge commit: 6e6a9fcf012a3304e18403adab898aca14937a0b

This project is alive again. @k-nut, if you're interested in contributing, please jump on board.

@melynnduh, it would be wonderful if you could add Allegheny County. Just take a look at how all the others are done and follow the pattern. Fork this project, get it working, and then open a pull quests.

**Comment by k-nut** [comment]
Thanks for the ping @specious. I'm definitely following the developments and am looking forward to this picking up steam again :)

**Pull request closed without merging**
