### PR TITLE
adding albuquerque neighborhoods

### PR DESCRIPTION
**Pull request by ethomas12**
Greetings from Sandy F. & Elaine T. who worked on this project together at the National Day of Civic Hacking - Code for America held at Fat Pipe ABQ in Albuquerque, NM, USA.

### CODE REVIEW

**Comment by ethomas12** [comment]
Greetings from Sandy F. & Elaine T. who worked on this project together at the National Day of Civic Hacking - Code for America held at Fat Pipe ABQ in Albuquerque, NM, USA.

**Comment by ethomas12** [comment]
Greetings from Sandy F. & Elaine T. who worked on this project together at the National Day of Civic Hacking - Code for America held at Fat Pipe ABQ in Albuquerque, NM, USA.

**Comment by ethomas12** [comment]
@mwichary, could you please review this?

**Comment by specious** [comment]
@ethomas12, thank you so much for your contribution to this project. I looked over your work and I cherry picked just the [data for Albuqueue](https://github.com/codeforgermany/click_that_hood/blob/master/public/data/albuquerque.geojson) for inclusion. 

The project is alive again, so please don't hesitate to contribute.

Merged commit: 7a2c358424ce7fdaf22ff4862c6fab492c4a07b8

**Pull request closed without merging**
